language: objective-c
osx_image: xcode7.3
rvm: 2.2

before_install:
   - sudo gem install cocoapods
   - pod repo update

script: xcodebuild -workspace CHCarouselView.xcworkspace -scheme CHCarouselView -sdk iphonesimulator